Repository Cookie-AutoDelete/Cookie-AutoDelete, pull requests merged in 2020-07, with the labels that each got.

#797 Fix help link for Keep Default Icon on all list types
  src/ui/settings/components/Settings.tsx
Labels: enhancement/ui

#815 chore(deps): Updates for 2020 July
  package-lock.json
  package.json
Labels: dependencies

#816 feat: Summary notifications
  extension/_locales/en/messages.json
  src/redux/Actions.ts
  src/services/CleanupService.ts
  src/services/StoreUser.ts
  src/ui/UILibs.tsx
  src/ui/settings/components/SideBar.tsx
Labels: enhancement, enhancement/ui
